// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjNkf5-zDjCOMKazEtY0XEa1Hl7vm8ISY',
    appId: '1:355375552754:web:942dc19ef43dc2d349586b',
    messagingSenderId: '355375552754',
    projectId: 'riffbyte',
    authDomain: 'riffbyte.firebaseapp.com',
    storageBucket: 'riffbyte.firebasestorage.app',
    measurementId: 'G-F3HZ5234DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJf97YmfCGORfNsFITJNN62uGAKQOmTY',
    appId: '1:355375552754:android:2ac9fd832af0cb2549586b',
    messagingSenderId: '355375552754',
    projectId: 'riffbyte',
    storageBucket: 'riffbyte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCktmFtXFsTmllfk53G_FBthGJxHzsVmqI',
    appId: '1:355375552754:ios:5b1703245837c70549586b',
    messagingSenderId: '355375552754',
    projectId: 'riffbyte',
    storageBucket: 'riffbyte.firebasestorage.app',
    iosBundleId: 'com.example.riffbyteWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCktmFtXFsTmllfk53G_FBthGJxHzsVmqI',
    appId: '1:355375552754:ios:5b1703245837c70549586b',
    messagingSenderId: '355375552754',
    projectId: 'riffbyte',
    storageBucket: 'riffbyte.firebasestorage.app',
    iosBundleId: 'com.example.riffbyteWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjNkf5-zDjCOMKazEtY0XEa1Hl7vm8ISY',
    appId: '1:355375552754:web:1d67504d66396c0d49586b',
    messagingSenderId: '355375552754',
    projectId: 'riffbyte',
    authDomain: 'riffbyte.firebaseapp.com',
    storageBucket: 'riffbyte.firebasestorage.app',
    measurementId: 'G-Q5NM3NHLW0',
  );
}
